### ISSUE TITLE
Error: .env file not found

### ISSUE THREAD

**Issue by Rueby** [ausboss/PygDiscordBot#15]
I edited the sample.env using Notepad++ by inserting the token as explained in the rentry, I grabbed the channel ID from discord using dev mode, I successfully added the bot to my server.

I'm running occ4m's 4bit fork of KoboldAI, I used the local link that I use to connect to in tavern. Did I miss something? Or does this not work with 4bit?

![image](https://github.com/ausboss/PygDiscordBot/assets/92205577/e5054c52-366a-436d-8fdc-fd0d95f2af81)

**Comment by ausboss** [comment]
I added something to the readme about the .env
