### ISSUE TITLE
how to increase/change tokens to generate?

### ISSUE THREAD

**Issue by Jake36921** [ausboss/PygDiscordBot#20]

**Comment by Mage-Enderman** [comment]
Same, I'd like to get it to generate 80 tokens at least opposed to just 50

**Comment by ausboss** [comment]
Open up cogs/pygbot.py and change the value. Max I think is 512.

**Comment by Mage-Enderman** [comment]
> 

value of what though? there's nothing referencing tokens for output and upping max length doesn't seem to do it

**Comment by Jake36921** [comment]
changed the max_length value to 250 yet it still generates 50 tokens

**Comment by unsureboolean** [comment]
Same, changing max_length does nothing. The bot still cuts off at 50 tokens

**Comment by Jake36921** [comment]
how do you exactly increase/change the amount to generate? I do know a bit of python but I don't seem to see what can affect/change the tokens to generate on pygbot.py

**Comment by unsureboolean** [comment]
@Jake36921 ehich model are you using? I had the same issue but switched to a different model and it fixed itself.

**Comment by Jake36921** [comment]
@unsureboolean I'm currently using [wizardlm-13b-v1.0-superhot-8k-ggml](https://huggingface.co/TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-GGML) and wdym it fixed itself?

**Comment by unsureboolean** [comment]
@Jake36921 Sorry if I wasn't clear, I meant that I stopped using the model I originally had loaded, and downloaded a different model instead. 

So for example, you're using [wizard](https://huggingface.co/TheBloke/WizardLM-13B-V1-0-Uncensored-SuperHOT-8K-GGML) If you switch to any other model if you're running 13b models, currently the highest ranked one on HF is [this](https://huggingface.co/NousResearch/Nous-Hermes-Llama2-13b) one here. Try using that one and see if you get longer responses. Like @ausboss mentioned above, you'll also need to adjust cogs/pygbot.py to the max value you want.
