### ISSUE TITLE
Instruct mode?

### ISSUE THREAD

**Issue by Mage-Enderman** [ausboss/PygDiscordBot#21]
Any way to change it to instruct mode as opposed to chat?
I feel like there should be a / command for it

**Comment by ausboss** [comment]
I have a branch where i am doing that kind of stuff, ive been neglecting my main branch because there is just too many AI related projects going on.

**Comment by ausboss** [comment]
you could go in to cogs/pygbot and change the prompt like this if it was alpaca instruct.
![image](https://github.com/ausboss/PygDiscordBot/assets/102309304/2a9b6853-d6f3-4d47-b307-6f9e91c19cf5)
