### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by sosiska123331827255** [ausboss/PygDiscordBot#24]
I encountered an error while using the Discord bot script (discordbot.py). The error message states: "AttributeError: 'NoneType' object has no attribute 'split'". This issue prevents the bot from functioning

if len(bot.endpoint.split("/api")) > 0:
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by ausboss** [comment]
did you set up the env with the url to the endpoint?https://github.com/ausboss/PygDiscordBot/raw/main/how-to-env.gif

**Comment by ausboss** [comment]
I also pushed a change just now that might fix
