### ISSUE TITLE
No Local GPU Docs

### ISSUE THREAD

**Issue by z3nith-source** [ausboss/PygDiscordBot#32]
There is a link that is supposed to show me how to use this locally on my GPU, but it does not lead anywhere.

**Comment by ausboss** [comment]
I recommend using this 

https://github.com/oobabooga/text-generation-webui#one-click-installers

after you install it you will want to run with the --api parameter, or select it in the webui. Then you can set the .evn endpoint as http://127.0.0.1:5000/ assuming that you are running it locally.
