### ISSUE TITLE
ExtensionFailed: Extension 'cogs.pygbot' raised an error: KeyError: 'name'

### ISSUE THREAD

**Issue by firelightning13** [ausboss/PygDiscordBot#5]
Not sure what happened here. There is an error regarding the `cogs.pygbot`. Using your latest branch btw.
Here's the log in my terminal output:
```bash
(env) [muzz@nobara-laptop PygDiscordBot]$ python discordbot.py 
1. Chiharu Yamada
2. Rise Kujikawa
3. Neuro sama
Please select a character: 3
Update Bot name and pic? (y or n): n
[nltk_data] Downloading package punkt to /home/muzz/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
ExtensionFailed: Extension 'cogs.pygbot' raised an error: KeyError: 'name'
2023-02-24 22:42:08 INFO     discord.client logging in using static token
2023-02-24 22:42:10 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 51c88715f42f6c5a1ec5ee11c533084a).
Neuro sama#7837 has connected to Discord!
2023-02-24 22:42:12 ERROR    discord.client Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/muzz/.conda/envs/env/lib/python3.9/site-packages/discord/client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "/home/muzz/build2/PygDiscordBot/discordbot.py", line 148, in on_message
    response = await bot.get_cog("chatbot").chat_command(message, message.content, bot)
AttributeError: 'NoneType' object has no attribute 'chat_command'
```

**Comment by ausboss** [comment]
I think this is related to the space in the bot name. I'm going to try and fix this. As a workaround, you could remove the space between Neuro and Sama and see if that fixes it.

**Comment by firelightning13** [comment]
Nope, it doesn't work even if I named her NeuroSama

**Comment by firelightning13** [comment]
Okay I see why, in `pygbot.py` in line 38, I changed `data["name"]` `data["char_name"]` and it worked now.

**Comment by ausboss** [comment]
> Okay I see why, in `pygbot.py` in line 38, I changed `data["name"]` to `data["char_name"]` and it worked now.
Glad you got it figured out. I actually was just testing out a Neuro Sama bot and the two names do work.

**Comment by ausboss** [comment]
It seems that was left over from when I was rewriting the whole thing. Good catch. I just did a commit to fix that.
